version: '3.5'

services:
  FS-postgres:
    container_name: FS-postgres
    ports:
      - "5432:5432"
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./FS-postgres_data:/var/lib/postgresql/data/
